import requests, pprint


sequence = """>jgi|Grifr1|12740|transcript:OBZ74161
MATDSLTLDVSPDDIPVNMIPCLTSLGATYNVLTGLYADARSCKQIVMDWNNAAYYETSF
GANGKVWAIPDSVNFQSYVNTLFASNHGESTEEYTKSLASRTELGAEYPFFTGSVSVDYS
SEETSSVANSFTRVMHNVNLYTLSLPPPLELQSLLRPAFKNVLDEADPIAIFEQYGTHVV
NSLTAGGRASFTFATDARKYTASESVEVAASLTVKFLMGQLSAEEKVKYAETISNFQTSS
TQRVLTQGGAPEYGNDSFLTHIGEWARSVEDYTAFVDFGSIPGFVPLWQLASTTSRQNVL
KDAYGQYCRDFVPQFQISGPYLRLTPVKSLDACGKMTLVSIEPSWNMYTYPPSVDDLYYV
SQPWSVGLLGFASTTYGAAISEIITGVLAPVVRWETVTTDSRYGRVWKGYGPNSDYVVLS
NVCYSLGGQPPAQPPTELVKSMRAIHRCALKAAKYANEFPLKGSSPGGSIWSVSEEEFDK
PINEKKISSPWRFTASGVAPLDDPYVWNMDEVVIR*
"""

payload = {"seqdb": "pdb", "algo":"phmmer", "seq":sequence}
headers = {"Expect":"", "accept":"html"}

url = "https://www.ebi.ac.uk/Tools/hmmer/search/phmmer"

r = requests.post(url, data=payload, headers=headers)
uuid = ""
score_url = "https://www.ebi.ac.uk/Tools/hmmer/results/"+uuid+"/score"
#request = requests.get("https://www.ebi.ac.uk/Tools/hmmer/results/A4A2A6CA-E3E0-11EF-8B0C-133DFC2088FC/score")
print(r.text)

#print(request.text)


